version: "2"
services:
  rau-backend:
    container_name: rau-backend
    image: rau-backend
  rau-messenger:
    container_name: rau-messenger
    image: rau-messenger
  neo4j:
    container_name: neo4j-rau
    image: neo4j:3.0
    network_mode: "bridge"
    environment:
          - NEO4J_dbms_security_procedures_unrestricted=apoc.*
          - NEO4J_apoc_import_file_enabled=true
          - NEO4J_dbms_shell_enabled=true
    ports:
     - "7474:7474"
     - "7687:7687"
    volumes:
     - ./db/dbms:/data/dbms