version: "2"
services:
  rau-backend:
    container_name: rau-backend
    image: rau-backend
  rau-messenger:
    container_name: rau-messenger
    image: rau-messenger
  neo4j:
    container_name: neo4j-rau
    image: neo4j:3.0
    environment:
      - NEO4J_AUTH=neo4j/root
      - NEO4J_dbms_connector_http_listen__address=:7474
      - NEO4J_dbms_connector_bolt_listen__address=:7687
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
    ports:
     - "7474:7474"
     - "7687:7687"
    volumes:
     - ./db/dbms:/data/dbms