version: "2"
services:
  rau-backend:
    container_name: rau-backend
    image: rau-backend
  rau-messenger:
    container_name: rau-messenger
    image: rau-messenger
  neo4j:
    container_name: neo4j-rau
    image: kbastani/docker-neo4j:latest
    ports:
     - "7474:7474"
     - "7687:7687"
    volumes:
     - ./db/dbms:/data/dbms